import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { HelmetProvider } from "react-helmet-async";
import { Toaster } from "sonner";
import "@/index.css";
import { AuthProvider } from "@/context/AuthContext";
import { TenantProvider } from "@/context/TenantContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { ProtectedRoute } from "@/components/site/ProtectedRoute";
import ErrorBoundary from "@/components/site/ErrorBoundary";
import AdminLogin from "@/pages/admin/AdminLogin";
import AdminLayout from "@/pages/admin/AdminLayout";
import AdminDashboard from "@/pages/admin/AdminDashboard";
import AdminBookings from "@/pages/admin/AdminBookings";
import AdminPayments from "@/pages/admin/AdminPayments";
import AdminTrips from "@/pages/admin/AdminTrips";
import AdminCommunities from "@/pages/admin/AdminCommunities";
import AdminRentals from "@/pages/admin/AdminRentals";
import AdminLandingBuilder from "@/pages/admin/AdminLandingBuilder";
import AdminWebsiteOverview from "@/pages/admin/website/AdminWebsiteOverview";
import AdminWebsiteTemplates from "@/pages/admin/website/AdminWebsiteTemplates";
import AdminWebsitePages from "@/pages/admin/website/AdminWebsitePages";
import AdminWebsiteNavigation from "@/pages/admin/website/AdminWebsiteNavigation";
import AdminWebsiteBranding from "@/pages/admin/website/AdminWebsiteBranding";
import AdminWebsiteDomain from "@/pages/admin/website/AdminWebsiteDomain";
import AdminWebsiteSEO from "@/pages/admin/website/AdminWebsiteSEO";
import AdminWebsiteAnalytics from "@/pages/admin/website/AdminWebsiteAnalytics";
import AdminWebsiteSettings from "@/pages/admin/website/AdminWebsiteSettings";
import TenantSubscription from "@/pages/admin/TenantSubscription";
import AISuperAdminCommandCenter from "@/pages/admin/AISuperAdminCommandCenter";
import AITrustRiskCenter from "@/pages/admin/AITrustRiskCenter";
import AIGrowthIntelligence from "@/pages/admin/AIGrowthIntelligence";
import SuperLayout from "@/pages/super/SuperLayout";
import SuperDashboard from "@/pages/super/SuperDashboard";
import SuperMasterData from "@/pages/super/SuperMasterData";
import SuperTenants from "@/pages/super/SuperTenants";
import SuperTenantDetail from "@/pages/super/SuperTenantDetail";
import SuperVendors from "@/pages/super/SuperVendors";
import SuperSubscriptions from "@/pages/super/SuperSubscriptions";
import SuperAdvertising from "@/pages/super/SuperAdvertising";
import SuperBillingRequests from "@/pages/super/SuperBillingRequests";
import SuperWebsitePlatform from "@/pages/super/SuperWebsitePlatform";
import SuperPayments from "@/pages/super/SuperPayments";
import SuperCustomerCare from "@/pages/super/SuperCustomerCare";
import SuperSettings from "@/pages/super/SuperSettings";
import SuperSecurity from "@/pages/super/SuperSecurity";
import SuperAIControl from "@/pages/super/SuperAIControl";
import SuperSEOControl from "@/pages/super/SuperSEOControl";
import SuperCommunity from "@/pages/super/SuperCommunity";
import SuperBackpackerOperations from "@/pages/super/SuperBackpackerOperations";
const queryClient = new QueryClient();
function App(){return <ThemeProvider><TenantProvider><AuthProvider><BrowserRouter><ErrorBoundary><HelmetProvider><QueryClientProvider client={queryClient}><Toaster richColors position="top-right"/><Routes>
<Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin" element={<ProtectedRoute adminOnly><AdminLayout/></ProtectedRoute>}><Route index element={<AdminDashboard/>}/><Route path="builder" element={<AdminLandingBuilder/>}/><Route path="website" element={<AdminWebsiteOverview/>}/><Route path="website/builder" element={<AdminLandingBuilder/>}/><Route path="website/templates" element={<AdminWebsiteTemplates/>}/><Route path="website/pages" element={<AdminWebsitePages/>}/><Route path="website/navigation" element={<AdminWebsiteNavigation/>}/><Route path="website/branding" element={<AdminWebsiteBranding/>}/><Route path="website/domain" element={<AdminWebsiteDomain/>}/><Route path="website/seo" element={<AdminWebsiteSEO/>}/><Route path="website/analytics" element={<AdminWebsiteAnalytics/>}/><Route path="website/settings" element={<AdminWebsiteSettings/>}/><Route path="bookings" element={<AdminBookings/>}/><Route path="payments" element={<AdminPayments/>}/><Route path="trips" element={<AdminTrips/>}/><Route path="communities" element={<AdminCommunities/>}/><Route path="rentals" element={<AdminRentals/>}/><Route path="subscription" element={<TenantSubscription/>}/><Route path="ai-command-center" element={<AISuperAdminCommandCenter/>}/><Route path="ai-growth-intelligence" element={<AIGrowthIntelligence/>}/><Route path="ai-trust-risk" element={<AITrustRiskCenter/>}/></Route>
<Route path="/super" element={<ProtectedRoute superOnly><SuperLayout/></ProtectedRoute>}><Route index element={<SuperDashboard/>}/><Route path="ai-command-center" element={<AISuperAdminCommandCenter/>}/><Route path="ai-growth-intelligence" element={<AIGrowthIntelligence/>}/><Route path="ai-trust-risk" element={<AITrustRiskCenter/>}/><Route path="master-data" element={<SuperMasterData/>}/><Route path="subscriptions" element={<SuperSubscriptions/>}/><Route path="advertising" element={<SuperAdvertising/>}/><Route path="billing-requests" element={<SuperBillingRequests/>}/><Route path="tenants" element={<SuperTenants/>}/><Route path="tenants/:id" element={<SuperTenantDetail/>}/><Route path="vendors" element={<SuperVendors/>}/><Route path="payments" element={<SuperPayments/>}/><Route path="website-platform" element={<SuperWebsitePlatform/>}/><Route path="customer-care" element={<SuperCustomerCare/>}/><Route path="security" element={<SuperSecurity/>}/><Route path="ai-control" element={<SuperAIControl/>}/><Route path="seo" element={<SuperSEOControl/>}/><Route path="community" element={<SuperCommunity/>}/><Route path="backpacker" element={<SuperBackpackerOperations/>}/><Route path="settings" element={<SuperSettings/>}/></Route>
<Route path="*" element={<Navigate to="/admin" replace/>}/></Routes></QueryClientProvider></HelmetProvider></ErrorBoundary></BrowserRouter></AuthProvider></TenantProvider></ThemeProvider>};export default App;