// 7 Template Landing Page Tenant Trexio Multitenant System

export const TENANT_LANDING_TEMPLATES = [
  {
    id: "template-1",
    name: "Nusantara Open Trip Express",
    category: "Open Trip & Travel Agency",
    badge: "Most Popular for Organizers",
    description: "Layout energik berfokus pada dorongan konversi, badge sisa kuota trip, countdown flash deal, dan integrasi ulasan traveler.",
    theme: {
      primaryColor: "#047857",
      secondaryColor: "#0284C7",
      accentColor: "#F59E0B",
      bgMode: "light",
      fontStyle: "font-sans",
    },
    sections: [
      {
        id: "hero",
        type: "hero",
        enabled: true,
        title: "Jelajahi Surga Tersembunyi Indonesia Bersama Open Trip Terpercaya",
        subtitle: "Garansi pasti berangkat, perlindungan asuransi trip lengkap, dan pemandu lokal berpengalaman di 50+ destinasi favorit.",
        badgeText: "⚡ FLASH SALE MINGGU INI - DISKON UP TO 35%",
        mainCtaText: "Cari & Booking Trip",
        secondaryCtaText: "Konsultasi WhatsApp",
        heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
        statsBadges: [
          { label: "Traveler Puas", value: "18,400+" },
          { label: "Destinasi Indonesia", value: "65+" },
          { label: "Rating Google & Trip", value: "4.9/5.0" },
        ],
      },
      {
        id: "badges",
        type: "badges",
        enabled: true,
        title: "Mengapa Memilih Kami?",
        items: [
          { icon: "ShieldCheck", title: "Garansi 100% Pasti Berangkat", desc: "Minimal 2 orang langsung jalan tanpa batas minimum kuota yang rumit." },
          { icon: "MoneyWavy", title: "Sistem Pembayaran Dijamin Aman", desc: "Mendukung Virtual Account, QRIS, GoPay, dan Kartu Kredit." },
          { icon: "UserCheck", title: "Pemandu Bersertifikat BNSP", desc: "Pemandu wisata lokal profesional, ramah, dan menguasai pertolongan pertama." },
          { icon: "Camera", title: "Free Foto & Dokumentasi Drone", desc: "Dapatkan file hasil foto dan video cinematic kualitas HD tanpa biaya tambahan." },
        ],
      },
      {
        id: "catalog",
        type: "catalog",
        enabled: true,
        title: "Katalog Open Trip Terfavorit",
        subtitle: "Pilih tanggal keberangkatan dan amankan kursi Anda sebelum kehabisan!",
        sampleTrips: [],
      },
      {
        id: "impact_or_metrics",
        type: "impact_or_metrics",
        enabled: true,
        title: "Statistik Keberhasilan Trip",
        subtitle: "Kepercayaan traveler adalah kebanggaan dan komitmen pelayanan kami.",
        metricItems: [
          { number: "99.8%", label: "Tingkat Kepuasan Pelanggan" },
          { number: "1,250+", label: "Trip Sukses Dijalankan" },
          { number: "100%", label: "Asuransi Perjalanan Tercover" },
          { number: "24/7", label: "Layanan Customer Support" },
        ],
      },
      {
        id: "testimonials",
        type: "testimonials",
        enabled: true,
        title: "Kata Mereka Tentang Pengalaman Trip",
        reviewItems: [
          {
            name: "Andi Pratama",
            role: "Solo Traveler - Jakarta",
            comment: "Trip Bromo-nya seru banget! Dokumentasi dronenya keren abis, tour guidenya ramah dan sangat membantu pas trekking.",
            rating: 5,
            avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
          },
          {
            name: "Siti Rahmawati",
            role: "Family Vacation - Surabaya",
            comment: "Booking di Trexio gampang banget, tinggal scan QRIS langsung dapet e-ticket & grup WhatsApp info keberangkatan.",
            rating: 5,
            avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
          },
        ],
      },
      {
        id: "gallery",
        type: "gallery",
        enabled: true,
        title: "Galeri Momen Traveler Kami",
        photos: [
          "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=80",
          "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=500&q=80",
          "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80",
          "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=500&q=80",
        ],
      },
      {
        id: "cta_banner",
        type: "cta_banner",
        enabled: true,
        title: "Siap Berpetualang Liburan Ini?",
        text: "Dapatkan promo potongan harga khusus pengguna baru dan merchandise gratis dari Trexio!",
        buttonLabel: "Pesan Tiket Trip Sekarang",
      },
      {
        id: "faq",
        type: "faq",
        enabled: true,
        title: "Pertanyaan Yang Sering Diajukan (FAQ)",
        faqItems: [
          { q: "Bagaimana sistem pembayarannya?", a: "Pembayaran melalui Trexio Dijamin Aman via Transfer Bank Virtual Account, QRIS, e-Wallet, dan Kartu Kredit." },
          { q: "Apakah ada garansi pembatalan?", a: "Pengembalian dana (refund) berlaku hingga H-7 keberangkatan sesuai dengan syarat & ketentuan yang berlaku." },
        ],
      },
    ],
  },

  {
    id: "template-2",
    name: "Wanderlust Eco-Expeditions",
    category: "Eco Tourism & Nature Conservation",
    badge: "Sustainable Travel",
    description: "Desain hijau alami bersahaja dengan highlight kontribusi konservasi, penanaman pohon, dan pemberdayaan masyarakat lokal.",
    theme: {
      primaryColor: "#15803D",
      secondaryColor: "#047857",
      accentColor: "#10B981",
      bgMode: "eco-tint",
      fontStyle: "font-sans",
    },
    sections: [
      {
        id: "hero",
        type: "hero",
        enabled: true,
        title: "Berwisata Tanpa Jejak, Melestarikan Keindahan Alam Indonesia",
        subtitle: "Setiap tiket keberangkatan Anda menyumbangkan 1 bibit pohon untuk penghijauan taman nasional dan mendukung ekonomi warga lokal.",
        badgeText: "🌱 CERTIFIED GREEN TOURISM & ZERO PLASTICS PLEDGE",
        mainCtaText: "Lihat Ekspedisi Hijau",
        secondaryCtaText: "Laporan Dampak Alam",
        heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
        statsBadges: [
          { label: "Pohon Ditanam", value: "14,200+" },
          { label: "Pemandu Lokal Didukung", value: "120 Guide" },
          { label: "Karbon Terkurangi", value: "45 Ton" },
        ],
      },
      {
        id: "badges",
        type: "badges",
        enabled: true,
        title: "Prinsip Wisata Berkelanjutan",
        items: [
          { icon: "Tree", title: "1 Paket = 1 Pohon Ditanam", desc: "Mitra resmi gerakan reboisasi hutan lindung dan mangrove nasional." },
          { icon: "Recycle", title: "Bebas Botol Plastik Sekali Pakai", desc: "Kami menyediakan tumbler dan refill station di sepanjang jalur trip." },
          { icon: "UsersThree", title: "Community First Tourism", desc: "100% konsumsi dan akomodasi menggunakan usaha masyarakat lokal." },
          { icon: "Heart", title: "Ekowisata Ramah Satwa", desc: "Tanpa eksploitasi satwa, mengutamakan observasi habitat alami secara etis." },
        ],
      },
      {
        id: "catalog",
        type: "catalog",
        enabled: true,
        title: "Paket Ekspedisi Alam & Konservasi",
        subtitle: "Rasakan kedamaian alam liar dengan bimbingan naturalis profesional.",
        sampleTrips: [],
      },
      {
        id: "impact_or_metrics",
        type: "impact_or_metrics",
        enabled: true,
        title: "Laporan Dampak Keberlanjutan",
        subtitle: "Langkah nyata bersama dalam menjaga warisan kekayaan hayati Nusantara.",
        metricItems: [
          { number: "14,200", label: "Bibit Pohon Ditanam" },
          { number: "88%", label: "Sampah Organik Diolah" },
          { number: "Rp 1,2 M", label: "Dana Diterima Warga Lokal" },
          { number: "25+", label: "Komunitas Konservasi" },
        ],
      },
      {
        id: "testimonials",
        type: "testimonials",
        enabled: true,
        title: "Ulasan Dari Sahabat Alam",
        reviewItems: [
          {
            name: "Dr. Maya Indah",
            role: "Peneliti Lingkungan",
            comment: "Sangat kagum dengan transparansi tim. Kita tidak hanya jalan-jalan, tapi ikut menanam bibit mangrove dan edukasi warga lokal.",
            rating: 5,
            avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80",
          },
        ],
      },
      {
        id: "cta_banner",
        type: "cta_banner",
        enabled: true,
        title: "Jadilah Bagian Dari Generasi Penyelamat Alam",
        text: "Daftar sekarang untuk perjalanan bermakna berikutnya dan dapatkan sertifikat partisipasi ekologis.",
        buttonLabel: "Pilih Destinasi Ramah Lingkungan",
      },
    ],
  },

  {
    id: "template-3",
    name: "Sail & Blue Archipelago",
    category: "Luxury Island & Marine Resort",
    badge: "Luxury & Yacht Charter",
    description: "Tampilan premium mewah warna biru samudera & aksen emas, ideal untuk persewaan phinisi, liveaboard, dan vila kepulauan eksklusif.",
    theme: {
      primaryColor: "#0369A1",
      secondaryColor: "#D97706",
      accentColor: "#38BDF8",
      bgMode: "dark-luxe",
      fontStyle: "font-serif",
    },
    sections: [
      {
        id: "hero",
        type: "hero",
        enabled: true,
        title: "Eksplorasi Mewah Kepulauan Indonesia Dengan Kapal Phinisi Privat",
        subtitle: "Nikmati pengalaman berlayar bintang lima, kuliner koki pribadi, layanan butler 24 jam, dan spot menyelam eksklusif Raja Ampat & Komodo.",
        badgeText: "🛥️ PRIVATE YACHT & LIVEABOARD LUXURY EXPERIENCE",
        mainCtaText: "Reservasi Phinisi Privat",
        secondaryCtaText: "Unduh Katalog VIP",
        heroImage: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
        statsBadges: [
          { label: "Armada Phinisi Luxury", value: "12 Kapal" },
          { label: "Bintang Layanan", value: "5/5 Star" },
          { label: "Koki & Butler", value: "Professional" },
        ],
      },
      {
        id: "badges",
        type: "badges",
        enabled: true,
        title: "Fasilitas Eksklusif VVIP",
        items: [
          { icon: "Crown", title: "Kabin Master Ocean View", desc: "Kamar tidur mewah ber-AC dengan balkon panorama laut 180 derajat." },
          { icon: "ForkKnife", title: "Koki Pribadi & Gourmet Seafood", desc: "Sajian kuliner segar internasional dan lokal racikan chef ternama." },
          { icon: "Waves", title: "Peralatan Diving & Water Sports Complete", desc: "Dilengkapi Jetski, Seabob, Transparent Kayak, dan perlengkapan selam profesional." },
          { icon: "ShieldCheck", title: "Kapten & Kru Bersertifikat Internasional", desc: "Standar keselamatan navigasi tinggi dan respon darurat teruji." },
        ],
      },
      {
        id: "catalog",
        type: "catalog",
        enabled: true,
        title: "Rute Pelayaran Eksklusif",
        subtitle: "Rencanakan liburan impian keluarga dan kolega Anda.",
        sampleTrips: [],
      },
      {
        id: "cta_banner",
        type: "cta_banner",
        enabled: true,
        title: "Jadwalkan Konsultasi Pelayaran Eksklusif Anda",
        text: "Tim VIP Concierge kami siap membantu merancang itinerary pelayaran sesuai keinginan pribadi Anda.",
        buttonLabel: "Hubungi Concierge VIP",
      },
    ],
  },

  {
    id: "template-4",
    name: "Summit Pioneers Trekking",
    category: "Mountain Trekking & Outdoor Peak",
    badge: "Outdoor & Mountaineering",
    description: "Desain gahar, tegas dengan warna slate & orange keselamatan. Dilengkapi indikator tingkat kesulitan, grafik elevasi, dan daftar perlengkapan.",
    theme: {
      primaryColor: "#DC2626",
      secondaryColor: "#1E293B",
      accentColor: "#EAB308",
      bgMode: "dark-slate",
      fontStyle: "font-sans",
    },
    sections: [
      {
        id: "hero",
        type: "hero",
        enabled: true,
        title: "Penakluk Puncak Nusantara: Ekspedisi Gunung Dengan Keamanan Utama",
        subtitle: "Porter terlatih, logistik makanan bergizi di ketinggian, standar medis tinggi, dan tim pemandu puncak bersertifikat teknis.",
        badgeText: "🏔️ MOUNTAIN SAFETY CERTIFIED & RESCUE GUARANTEED",
        mainCtaText: "Pilih Jadwal Pendakian",
        secondaryCtaText: "Cek Checklist Perlengkapan",
        heroImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
        statsBadges: [
          { label: "Puncak Berhasil Ditempuh", value: "3,800+ Hiker" },
          { label: "Tingkat Keberhasilan Summit", value: "96.4%" },
          { label: "Tim Medis & Porter", value: "Profesional" },
        ],
      },
      {
        id: "badges",
        type: "badges",
        enabled: true,
        title: "Standar Ekspedisi Puncak Kami",
        items: [
          { icon: "FirstAid", title: "Peralatan Medis & Oksigen Tabung", desc: "Setiap rombongan dibekali pulse oximeter, pertolongan AMS, dan tim medis pendamping." },
          { icon: "CookingPot", title: "Menu Nutrisi Tinggi Di Basecamp", desc: "Makanan segar bergizi hangat disajikan rutin 3x sehari oleh koki lapangan." },
          { icon: "ShieldWarning", title: "Tenda Badai Double Layer & Sleeping Bag Warm", desc: "Peralatan camping kelas ekspedisi tahan cuaca ekstrem ketinggian 3.000+ MDPL." },
          { icon: "Compass", title: "Satelit GPS Communicator", desc: "Sistem pelacakan posisi real-time dan komunikasi darurat satelit tanpa sinyal seluler." },
        ],
      },
      {
        id: "catalog",
        type: "catalog",
        enabled: true,
        title: "Jadwal Ekspedisi Puncak Gunung",
        subtitle: "Sesuaikan dengan fisik dan jam terbang pendakian Anda.",
        sampleTrips: [],
      },
      {
        id: "cta_banner",
        type: "cta_banner",
        enabled: true,
        title: "Siapkan Fisik & Taklukkan Puncak Impian Anda!",
        text: "Dapatkan program latihan fisik gratis dan konsultasi gearing gratis sebelum tanggal pendakian.",
        buttonLabel: "Daftar Pendakian Sekarang",
      },
    ],
  },

  {
    id: "template-5",
    name: "Trexio Corporate Ventures",
    category: "Corporate Outbound & Team Building",
    badge: "B2B & Corporate Event",
    description: "Desain profesional bergaya B2B executive. Dilengkapi marquee logo klien enterprise, kalkulator perkiraan anggaran peserta, dan tombol unduh proposal PDF.",
    theme: {
      primaryColor: "#4F46E5",
      secondaryColor: "#0284C7",
      accentColor: "#10B981",
      bgMode: "light",
      fontStyle: "font-sans",
    },
    sections: [
      {
        id: "hero",
        type: "hero",
        enabled: true,
        title: "Solusi Corporate Gathering, Outbound & Offsite Team Building Terbaik",
        subtitle: "Tingkatkan kolaborasi, produktivitas, dan moral karyawan perusahaan Anda dengan acara luar ruangan yang seru, aman, dan berkesan.",
        badgeText: "🏢 TRUSTED BY 250+ TOP ENTERPRISE & MULTINATIONAL COMPANIES",
        mainCtaText: "Minta Penawaran / Proposal",
        secondaryCtaText: "Hitung Estimasi Biaya",
        heroImage: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=80",
        statsBadges: [
          { label: "Perusahaan Dilayani", value: "250+ Klien" },
          { label: "Peserta Outbound", value: "45,000+" },
          { label: "Faktur Pajak & Legaltas", value: "Lengkap (PT)" },
        ],
      },
      {
        id: "badges",
        type: "badges",
        enabled: true,
        title: "Mengapa Perusahaan Memilih Kami?",
        items: [
          { icon: "FileText", title: "Proposal Rinci & Legalitas PT Resmi", desc: "Siap dengan dokumen tender, faktur pajak PPN, dan termin pembayaran fleksibel B2B." },
          { icon: "UsersThree", title: "Master Facilitator & HR Games Specialist", desc: "Merancang simulasi experiential learning yang sejalan dengan nilai Budaya Perusahaan." },
          { icon: "Briefcase", title: "Custom Theme & Branding Perusahaan", desc: "Kaos seragam, spanduk banner, merchandise, hingga foto/video dokumentasi berkualiti tinggi." },
          { icon: "ShieldCheck", title: "Asuransi Group & Manajemen Risiko K3", desc: "Prosedur keselamatan ketat dengan dukungan ambulans siaga di lokasi acara." },
        ],
      },
      {
        id: "catalog",
        type: "catalog",
        enabled: true,
        title: "Pilihan Program Corporate Outbound",
        subtitle: "Dapat disesuaikan sepenuhnya dengan durasi dan anggaran divisi Anda.",
        sampleTrips: [],
      },
      {
        id: "cta_banner",
        type: "cta_banner",
        enabled: true,
        title: "Rencanakan Event Perusahaan Anda Sekarang",
        text: "Hubungi tim B2B Corporate Specialist kami untuk mendapatkan proposal penawaran khusus dalam 24 jam.",
        buttonLabel: "Hubungi Account Executive B2B",
      },
    ],
  },

  {
    id: "template-6",
    name: "Nusantara Heritage Trails",
    category: "Cultural & Heritage Voyages",
    badge: "Culture & Heritage",
    description: "Nuansa terracotta hangat dan kertas perkamen tua. Menampilkan garis waktu sejarah, workshop pengrajin lokal, dan jalur kuliner otentik.",
    theme: {
      primaryColor: "#9A3412",
      secondaryColor: "#78350F",
      accentColor: "#D97706",
      bgMode: "warm-parchment",
      fontStyle: "font-serif",
    },
    sections: [
      {
        id: "hero",
        type: "hero",
        enabled: true,
        title: "Menelusuri Jejak Sejarah & Kekayaan Budaya Luhur Nusantara",
        subtitle: "Menyelami kisah maestro batik, kerajinan seni lokal, candi megah, dan kelezatan kuliner warisan leluhur Indonesia.",
        badgeText: "🏛️ CULTURAL HERITAGE TOURS & ARTISAN WORKSHOPS",
        mainCtaText: "Jelajahi Paket Budaya",
        secondaryCtaText: "Jadwal Workshop Seni",
        heroImage: "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80",
        statsBadges: [
          { label: "Desa Wisata Budaya", value: "35 Desa" },
          { label: "Maestro & Pengrajin", value: "80+ Tokoh" },
          { label: "Rating Pengalaman", value: "4.9/5.0" },
        ],
      },
      {
        id: "badges",
        type: "badges",
        enabled: true,
        title: "Pengalaman Otentik Nusantara",
        items: [
          { icon: "Palette", title: "Praktik Langsung Membatik Tulis", desc: "Belajar membuat kain batik dari canting hingga pewarnaan alami bersama empu." },
          { icon: "CookingPot", title: "Culinary Heritage Tasting", desc: "Menikmati racikan jamu tradisional dan santapan autentik resep keraton." },
          { icon: "Scroll", title: "Pemandu Sejarawan & Budayawan", desc: "Ditemani sejarawan lokal yang memahami filosofi serta cerita mendalam di tiap situs." },
          { icon: "HouseSimple", title: "Menginap Di Rumah Adat Warga", desc: "Merasakan kehangatan kearifan lokal di hamparan desa adat yang asri." },
        ],
      },
      {
        id: "catalog",
        type: "catalog",
        enabled: true,
        title: "Rute Perjalanan Budaya Pilihan",
        subtitle: "Petualangan edukatif dan bermakna untuk semua usia.",
        sampleTrips: [],
      },
      {
        id: "cta_banner",
        type: "cta_banner",
        enabled: true,
        title: "Lestarikan Budaya Nusantara Bersama Kami",
        text: "Dapatkan cinderamata kerajinan tangan lokal gratis untuk setiap pemesanan rombongan keluarga.",
        buttonLabel: "Pesan Paket Wisata Budaya",
      },
    ],
  },

  {
    id: "template-7",
    name: "Getaway Express Bento",
    category: "Weekend Getaways & Flash Deals",
    badge: "Flash Sales & Bento Layout",
    description: "Layout bento modern resolusi tinggi, sangat cocok untuk generasi muda, liburan singkat akhir pekan, dan trip Instagrammable.",
    theme: {
      primaryColor: "#EC4899",
      secondaryColor: "#8B5CF6",
      accentColor: "#F43F5E",
      bgMode: "dark-neon",
      fontStyle: "font-sans",
    },
    sections: [
      {
        id: "hero",
        type: "hero",
        enabled: true,
        title: "Bosan Kerja? Kabur Sejenak Di Weekend Getaway Cepat & Anti Ribet!",
        subtitle: "Cukup 1 klik pesan tiket, tempat duduk dijamin aman, siap dijemput dari meeting point kota Anda.",
        badgeText: "🔥 FLASH SALE CHAT WHATSAPP INSTAN - SEAT TERBATAS!",
        mainCtaText: "Cek Trip Weekend Ini",
        secondaryCtaText: "Chat Admin WhatsApp",
        heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
        statsBadges: [
          { label: "Keberangkatan", value: "Tiap Sabtu/Minggu" },
          { label: "Slot Tersisa Hari Ini", value: "5 Seat" },
          { label: "Waktu Respon WA", value: "< 2 Menit" },
        ],
      },
      {
        id: "badges",
        type: "badges",
        enabled: true,
        title: "Kenapa Anak Muda Pilih Kita?",
        items: [
          { icon: "Lightning", title: "Pesan 1 Menit Langsung Berangkat", desc: "Tanpa formulir berbelit-belit, bayar via QRIS otomatis terkonfirmasi." },
          { icon: "InstagramLogo", title: "Foto & Reel Instagram Ready", desc: "Guide pintar bantu ambil sudut foto estetik untuk konten media sosialmu." },
          { icon: "Smiley", title: "Teman Baru & Komunitas Seru", desc: "Suasana santai dan akrab bagi para solo traveler maupun kelompok kecil." },
          { icon: "Sparkle", title: "All Inclusive Tanpa Biaya Tersembunyi", desc: "Sudah termasuk tiket masuk objek, makan, transportasi, dan perlindungan asuransi." },
        ],
      },
      {
        id: "catalog",
        type: "catalog",
        enabled: true,
        title: "Getaway Deals Minggu Ini",
        subtitle: "Buruan amankan slot sebelum sold out!",
        sampleTrips: [],
      },
      {
        id: "cta_banner",
        type: "cta_banner",
        enabled: true,
        title: "Mulai Petualangan Akhir Pekanmu Sekarang!",
        text: "Dapatkan voucher potongan Rp 50.000 langsung di pemesanan pertamamu via WhatsApp.",
        buttonLabel: "Klaim Voucher & Chat WA",
      },
    ],
  },
];
