CREATE TABLE IF NOT EXISTS public.ai_trail_statuses (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_trail_statuses_updated_at_idx ON public.ai_trail_statuses(updated_at);
ALTER TABLE public.ai_trail_statuses ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_trail_statuses FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_official_alerts (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_official_alerts_updated_at_idx ON public.ai_official_alerts(updated_at);
ALTER TABLE public.ai_official_alerts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_official_alerts FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_user_checklists (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_user_checklists_updated_at_idx ON public.ai_user_checklists(updated_at);
ALTER TABLE public.ai_user_checklists ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_user_checklists FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_safety_config (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_safety_config_updated_at_idx ON public.ai_safety_config(updated_at);
ALTER TABLE public.ai_safety_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_safety_config FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_golden_dataset (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_golden_dataset_updated_at_idx ON public.ai_golden_dataset(updated_at);
ALTER TABLE public.ai_golden_dataset ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_golden_dataset FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_traces (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_traces_updated_at_idx ON public.ai_traces(updated_at);
ALTER TABLE public.ai_traces ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_traces FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_user_feedback (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_user_feedback_updated_at_idx ON public.ai_user_feedback(updated_at);
ALTER TABLE public.ai_user_feedback ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_user_feedback FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_alerts (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_alerts_updated_at_idx ON public.ai_alerts(updated_at);
ALTER TABLE public.ai_alerts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_alerts FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_regression_reports (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_regression_reports_updated_at_idx ON public.ai_regression_reports(updated_at);
ALTER TABLE public.ai_regression_reports ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_regression_reports FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_event_logs (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_event_logs_updated_at_idx ON public.ai_event_logs(updated_at);
ALTER TABLE public.ai_event_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_event_logs FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_feature_flags (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_feature_flags_updated_at_idx ON public.ai_feature_flags(updated_at);
ALTER TABLE public.ai_feature_flags ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_feature_flags FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_homepage_ranking_config (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_homepage_ranking_config_updated_at_idx ON public.ai_homepage_ranking_config(updated_at);
ALTER TABLE public.ai_homepage_ranking_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_homepage_ranking_config FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_recommendation_config (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_recommendation_config_updated_at_idx ON public.ai_recommendation_config(updated_at);
ALTER TABLE public.ai_recommendation_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_recommendation_config FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_articles (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_articles_updated_at_idx ON public.ai_articles(updated_at);
ALTER TABLE public.ai_articles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_articles FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_seo_config (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_seo_config_updated_at_idx ON public.ai_seo_config(updated_at);
ALTER TABLE public.ai_seo_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_seo_config FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_news_sources (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_news_sources_updated_at_idx ON public.ai_news_sources(updated_at);
ALTER TABLE public.ai_news_sources ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_news_sources FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_search_config (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_search_config_updated_at_idx ON public.ai_search_config(updated_at);
ALTER TABLE public.ai_search_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_search_config FROM anon, authenticated;
CREATE TABLE IF NOT EXISTS public.ai_usage_logs (id text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_usage_logs_updated_at_idx ON public.ai_usage_logs(updated_at);
ALTER TABLE public.ai_usage_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_usage_logs FROM anon, authenticated;