/**
 * TREXIO AI ENGINE - TYPES & CONSTANTS
 * Centralized constants, feature flag definitions, event types, and data structure schemas.
 */

const AI_FEATURE_FLAGS = {
  AI_RECOMMENDATION: 'AI_RECOMMENDATION',
  AI_HOMEPAGE: 'AI_HOMEPAGE',
  AI_SEARCH: 'AI_SEARCH',
  AI_ASSISTANT: 'AI_ASSISTANT',
  AI_VENDOR_RANKING: 'AI_VENDOR_RANKING',
  AI_SAFETY: 'AI_SAFETY',
  AI_FRAUD: 'AI_FRAUD',
  AI_ANALYTICS: 'AI_ANALYTICS',
  AI_VENDOR_COPILOT: 'AI_VENDOR_COPILOT',
};

const AI_EVENT_TYPES = {
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  TRIP_VIEW: 'TRIP_VIEW',
  SEARCH: 'SEARCH',
  CATEGORY_VIEW: 'CATEGORY_VIEW',
  DESTINATION_VIEW: 'DESTINATION_VIEW',
  WISHLIST_ADD: 'WISHLIST_ADD',
  WISHLIST_REMOVE: 'WISHLIST_REMOVE',
  BOOKING_STARTED: 'BOOKING_STARTED',
  BOOKING_COMPLETED: 'BOOKING_COMPLETED',
  REVIEW_CREATED: 'REVIEW_CREATED',
  RECOMMENDATION_IMPRESSION: 'RECOMMENDATION_IMPRESSION',
  RECOMMENDATION_CLICK: 'RECOMMENDATION_CLICK',
  RECOMMENDATION_WISHLIST: 'RECOMMENDATION_WISHLIST',
  RECOMMENDATION_BOOKING: 'RECOMMENDATION_BOOKING',
  RECOMMENDATION_DISMISS: 'RECOMMENDATION_DISMISS',
};

// Model constants as per Google GenAI SDK standards
const AI_MODELS = {
  GEMINI_FLASH: 'gemini-3.6-flash',
  GEMINI_PRO: 'gemini-3.1-pro-preview',
  GEMINI_LITE: 'gemini-3.1-flash-lite',
};

// Estimated pricing per 1,000 tokens (USD) for cost monitoring
const MODEL_PRICING = {
  'gemini-3.6-flash': { inputPer1k: 0.000075, outputPer1k: 0.0003 },
  'gemini-3.1-pro-preview': { inputPer1k: 0.00125, outputPer1k: 0.005 },
  'gemini-3.1-flash-lite': { inputPer1k: 0.000025, outputPer1k: 0.0001 },
};

const GROUNDING_STATUS = {
  SUPPORTED: 'SUPPORTED',
  PARTIALLY_SUPPORTED: 'PARTIALLY_SUPPORTED',
  UNSUPPORTED: 'UNSUPPORTED',
  UNVERIFIABLE: 'UNVERIFIABLE',
};

const QUALITY_GATE = {
  PASS: 'PASS',
  WARNING: 'WARNING',
  FAIL: 'FAIL',
};

const ALERT_SEVERITY = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

module.exports = {
  AI_FEATURE_FLAGS,
  AI_EVENT_TYPES,
  AI_MODELS,
  MODEL_PRICING,
  GROUNDING_STATUS,
  QUALITY_GATE,
  ALERT_SEVERITY,
};
